import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Somos Contacto",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="in">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
      <body className={inter.className}>
        
    <Navbar/>
        {children}

       

        <Footer/>
        
        </body>
      
    </html>
  );
}
