import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./components/Footer";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Somos Contacto",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="in">


<link rel="icon" href="/Logo.png"/>


{/* Vincula los iconos de diferentes tamaños */}
<link rel="apple-touch-icon"  sizes="180x180" href="/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
<link rel="manifest" className="rounded-full" href="/site.webmanifest" />
   
      <body className={inter.className}>
        
    <Navbar/>
        {children}

       

        <Footer/>
        
        </body>
      
    </html>
  );
}
